name: enough_convert
description: Support for character encodings / charsets / codecs missing from `dart:convert` - ISO 8859 / Latin, Windows, GBK, Big5, and KOI8 R/U.
version: 1.5.0
homepage: https://github.com/Enough-Software/enough_convert

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  characters: ^1.0.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.5
